import React, { useState } from 'react'
import Head from 'next/Head'
import Styled from './index.style'
import Sidebar from 'components/Sidebar'
import { ArrowRight } from 'ultils/icon'

interface Props {
  title?: string
  fullWidth?: boolean
  children: React.ReactChild | React.ReactChildren
}

const Layout = ({ title, fullWidth, children }: Props) => {
  const [showSidebar, setShowSidebar] = useState<boolean>(false)
  return (
    <>
      <Head>
        <title>{title || 'mTest'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Styled.Layout>
        <Styled.SidebarRegion active={showSidebar}>
          <Sidebar />
        </Styled.SidebarRegion>
        <Styled.SidebarToggle onClick={() => setShowSidebar(!showSidebar)}>
          {showSidebar ? 'Ẩn' : <ArrowRight />}
        </Styled.SidebarToggle>
        <Styled.MainRegion>
          <Styled.Main fullWidth={fullWidth}>{children}</Styled.Main>
        </Styled.MainRegion>
      </Styled.Layout>
    </>
  )
}

export default Layout
